server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index pages/admin/login.html;

  location = /healthz {
    add_header content-type text/plain;
    return 200 "ok";
  }

  location / {
    try_files $uri $uri/ /pages/admin/login.html;
  }

  location /assets/ {
    try_files $uri =404;
    add_header cache-control "public, max-age=31536000, immutable";
  }
}
